# Generated by Django 5.1.7 on 2025-07-26 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECCKeyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key_encrypted', models.TextField(help_text='Password-encrypted private key in JSON format')),
                ('public_key', models.TextField(help_text='PEM-encoded public key')),
                ('curve_name', models.CharField(choices=[('P-256', 'NIST P-256 (Recommended)'), ('P-384', 'NIST P-384 (High Security)'), ('secp256k1', 'secp256k1 (Bitcoin Curve)')], default='P-256', help_text='Elliptic curve used for this key pair', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('key_version', models.IntegerField(default=1)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.IntegerField(default=0)),
                ('rotation_due_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecc_keypair', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ECC Key Pair',
                'verbose_name_plural': 'ECC Key Pairs',
            },
        ),
        migrations.CreateModel(
            name='KeyRotationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_key_version', models.IntegerField()),
                ('new_key_version', models.IntegerField()),
                ('rotation_reason', models.CharField(choices=[('scheduled', 'Scheduled Rotation'), ('security_breach', 'Security Breach'), ('user_request', 'User Request'), ('admin_forced', 'Administrator Forced')], max_length=100)),
                ('rotated_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_rotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rotated_at'],
            },
        ),
    ]
