# Generated by Django 5.2.4 on 2025-08-17 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryFileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('encrypted_data', models.JSONField()),
                ('ephemeral_private_key', models.TextField()),
                ('ephemeral_public_key', models.TextField()),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('max_downloads', models.IntegerField(default=1)),
                ('download_count', models.IntegerField(default=0)),
                ('password_protected', models.BooleanField(default=False)),
                ('share_password', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'is_active'], name='qshare_temp_token_d8eef7_idx'), models.Index(fields=['expires_at', 'is_active'], name='qshare_temp_expires_1dd0d0_idx'), models.Index(fields=['uploader', '-created_at'], name='qshare_temp_uploade_e7da24_idx')],
            },
        ),
    ]
