# Generated by Django 5.1.7 on 2025-07-27 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('encrypted_file_path', models.CharField(max_length=500)),
                ('original_size', models.BigIntegerField(help_text='Original file size in bytes')),
                ('encrypted_size', models.BigIntegerField(help_text='Encrypted file size in bytes')),
                ('encryption_algorithm', models.CharField(choices=[('ECC-AES-256-GCM', 'ECC + AES-256-GCM'), ('ECC-AES-256-GCM-CHUNKED', 'ECC + AES-256-GCM (Chunked)')], max_length=30)),
                ('curve_name', models.CharField(default='P-256', max_length=20)),
                ('is_chunked', models.BooleanField(default=False)),
                ('file_hash', models.CharField(help_text='SHA-256 hash of original file', max_length=64)),
                ('digital_signature', models.TextField(help_text='Base64-encoded digital signature')),
                ('metadata', models.TextField(help_text='JSON-encoded file metadata')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_secure_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secure File',
                'verbose_name_plural': 'Secure Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SecureFileAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_download', models.BooleanField(default=True)),
                ('can_share', models.BooleanField(default=False)),
                ('access_granted_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granted_file_access', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.securefile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secure File Access',
                'verbose_name_plural': 'Secure File Access Records',
                'unique_together': {('file', 'user')},
            },
        ),
        migrations.AddField(
            model_name='securefile',
            name='allowed_users',
            field=models.ManyToManyField(related_name='accessible_secure_files', through='blog.SecureFileAccess', to=settings.AUTH_USER_MODEL),
        ),
    ]
