# Generated by Django 5.2.4 on 2025-08-03 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postgroupshare_postshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='securefile',
            name='allowed_users',
            field=models.ManyToManyField(related_name='accessible_secure_files', through='blog.SecureFileAccess', through_fields=('file', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
