# Generated by Django 5.2.4 on 2025-08-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_temporaryfileshare'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postshare',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postshare',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postshare',
            name='shared_by',
        ),
        migrations.RemoveField(
            model_name='postshare',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='securefile',
            name='allowed_users',
        ),
        migrations.RemoveField(
            model_name='securefile',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='securefileaccess',
            name='file',
        ),
        migrations.AlterUniqueTogether(
            name='securefileaccess',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='securefileaccess',
            name='access_granted_by',
        ),
        migrations.RemoveField(
            model_name='securefileaccess',
            name='user',
        ),
        migrations.RemoveField(
            model_name='temporaryfileshare',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='PostGroupShare',
        ),
        migrations.DeleteModel(
            name='PostShare',
        ),
        migrations.DeleteModel(
            name='SecureFile',
        ),
        migrations.DeleteModel(
            name='SecureFileAccess',
        ),
        migrations.DeleteModel(
            name='TemporaryFileShare',
        ),
    ]
