# Generated by Django 5.2.4 on 2025-08-17 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_postshare_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('encrypted_file_path', models.CharField(max_length=500)),
                ('original_size', models.BigIntegerField()),
                ('encrypted_size', models.BigIntegerField()),
                ('encryption_algorithm', models.CharField(choices=[('ECC-AES-256-GCM', 'ECC + AES-256-GCM'), ('ECC-AES-256-GCM-CHUNKED', 'ECC + AES-256-GCM (Chunked)')], max_length=30)),
                ('curve_name', models.CharField(default='P-256', max_length=20)),
                ('is_chunked', models.BooleanField(default=False)),
                ('file_hash', models.CharField(max_length=64)),
                ('digital_signature', models.TextField()),
                ('metadata', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_secure_files_blog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secure File (Blog)',
                'verbose_name_plural': 'Secure Files (Blog)',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SecureFileAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_download', models.BooleanField(default=True)),
                ('can_share', models.BooleanField(default=False)),
                ('access_granted_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granted_file_access_blog', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.securefile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securefileaccess_blog_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secure File Access (Blog)',
                'verbose_name_plural': 'Secure File Access Records (Blog)',
                'unique_together': {('file', 'user')},
            },
        ),
        migrations.AddField(
            model_name='securefile',
            name='allowed_users',
            field=models.ManyToManyField(related_name='accessible_secure_files_blog', through='blog.SecureFileAccess', through_fields=('file', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TemporaryFileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('encrypted_data', models.JSONField()),
                ('ephemeral_private_key', models.TextField()),
                ('ephemeral_public_key', models.TextField()),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('max_downloads', models.IntegerField(default=1)),
                ('download_count', models.IntegerField(default=0)),
                ('password_protected', models.BooleanField(default=False)),
                ('share_password', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_shares_blog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Temporary File Share (Blog)',
                'verbose_name_plural': 'Temporary File Shares (Blog)',
                'ordering': ['-created_at'],
            },
        ),
    ]
